version: '3.3'

services:
  db:
    container_name: users-db
    image: mongo
    ports:
      - "27017:27017"

  api:
    container_name: users-api
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=users_db

