version: '3.3'

services:
  db:
    container_name: users-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=users
      - MYSQL_RANDOM_ROOT_PASSWORD=true

  api:
    container_name: users-api
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - MYSQL_URI=mysql://db:3306

